expenses/dealcard/urls.py
from django.urls import path
from . import views

app_name = 'dealcard'

urlpatterns = [
    path('', views.card, name='card'),
    path('expense/add/', views.add_expense, name='add_expense'),
    path('expense/<int:expense_id>/edit/', views.edit_expense,
         name='edit_expense'),
    path('expense/<int:expense_id>/delete/', views.delete_expense,
         name='delete_expense'),
]

expenses/expenses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainpage.urls', namespace='mainpage')),
    path('card/', include('dealcard.urls', namespace='dealcard')),
    path('admin/', admin.site.urls),
    path('reports/', include('reports.urls', namespace='reports')),
]

expenses/reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'

urlpatterns = [
    path('finance/', views.report_finance, name='report_finance'),
    path('buh/', views.report_buh, name='report_buh')
]

expenses/dealcard/models.py
from django.db import models

from mainpage.models import Portals, CostItems


class CompaniesExpense(models.Model):
    """Класс Компаний из Битрикс24, которые могут иметь затраты"""

    id_b24 = models.IntegerField(
        verbose_name='ID компании в Битрикс24',
    )
    name = models.CharField(
        verbose_name='Наименование компании',
        max_length=255,
    )
    portal = models.ForeignKey(
        Portals,
        verbose_name='Портал',
        on_delete=models.PROTECT,
    )

    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'
        unique_together = ['id_b24', 'portal']
        ordering = ['portal']

    def __str__(self):
        return self.name


class Cargo(models.Model):
    """Класс полученных грузов из Битрикс24"""

    id_b24 = models.IntegerField(
        verbose_name='ID компании в Битрикс24',
    )
    number = models.CharField(
        verbose_name='Номер груза',
        max_length=10
    )
    portal = models.ForeignKey(
        Portals,
        verbose_name='Портал',
        on_delete=models.PROTECT,
    )
    deal_id = models.IntegerField(
        verbose_name='ID сделки в Битрикс24'
    )

    class Meta:
        verbose_name = 'Груз'
        verbose_name_plural = 'Грузы'
        unique_together = ['id_b24', 'portal']
        ordering = ['portal', 'deal_id']

    def __str__(self):
        return self.number


class Employee(models.Model):
    """Класс сотрудников из Битрикс24"""

    id_b24 = models.IntegerField(
        verbose_name='ID сотрудника в Битрикс24',
    )
    name = models.CharField(
        verbose_name='Имя',
        max_length=50,
    )
    last_name = models.CharField(
        verbose_name='Фамилия',
        max_length=50,
    )
    portal = models.ForeignKey(
        Portals,
        verbose_name='Портал',
        on_delete=models.PROTECT,
    )

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'
        unique_together = ['id_b24', 'portal']
        ordering = ['portal']

    def full_name(self):
        return f'{self.name} {self.last_name}'

    def __str__(self):
        return self.full_name()


class Expenses(models.Model):
    product_id = models.IntegerField(
        verbose_name='ID услуги',
    )
    cost_item = models.ForeignKey(
        CostItems,
        verbose_name='Статья затрат',
        on_delete=models.PROTECT,
        related_name='cost_items',
    )
    deal_id = models.IntegerField(
        verbose_name='ID сделки',
    )
    count = models.DecimalField(
        verbose_name='Количество',
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
    )
    price = models.DecimalField(
        verbose_name='Цена',
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
    )
    expense = models.DecimalField(
        verbose_name='Сумма',
        max_digits=12,
        decimal_places=2,
        null=True,
    )
    cargo = models.ForeignKey(
        Cargo,
        verbose_name='Груз',
        on_delete=models.PROTECT,
        blank=True,
        null=True,
    )
    company = models.ForeignKey(
        CompaniesExpense,
        verbose_name='Компания',
        on_delete=models.PROTECT,
        blank=True,
        null=True,
    )
    employee = models.ForeignKey(
        Employee,
        verbose_name='Сотрудник',
        on_delete=models.PROTECT,
        blank=True,
        null=True,
        related_name='employee'
    )
    type_cost = models.CharField(
        verbose_name='Вид оплаты',
        max_length=50,
        choices=[
            ('Наличный (карты)', 'Наличный (карты)'),
            ('Расчетный счет', 'Расчетный счет'),
            ('В кассу', 'В кассу'),
        ],
        blank=True,
        null=True,
    )
    document = models.CharField(
        verbose_name='Документ',
        max_length=255,
        blank=True,
        null=True,
    )
    create_date = models.DateTimeField(
        verbose_name='Дата создания',
        auto_now_add=True,
    )
    update_date = models.DateTimeField(
        verbose_name='Дата изменения',
        auto_now=True,
    )
    owner = models.ForeignKey(
        Employee,
        verbose_name='Создатель',
        on_delete=models.PROTECT,
        related_name='owner',
    )
    portal = models.ForeignKey(
        Portals,
        verbose_name='Портал',
        on_delete=models.PROTECT,
    )

    class Meta:
        verbose_name = 'Затраты'
        verbose_name_plural = 'Затраты'
        ordering = ['update_date']

    def __str__(self):
        return 'Затраты #{pk}'.format(pk=self.pk)


class Deal(models.Model):
    """Класс для хранения информации по сделкам Битрикс24."""
    deal_id = models.PositiveIntegerField(
        verbose_name='ID сделки',
        help_text='ID сделки из Битрикс24',
    )
    portal = models.ForeignKey(
        Portals,
        verbose_name='Портал',
        on_delete=models.PROTECT,
    )
    proceeds = models.DecimalField(
        verbose_name='Выручка',
        help_text='Сумма сделки',
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
    )
    sum_expenses = models.DecimalField(
        verbose_name='Затраты',
        help_text='Сумма затрат по сделке',
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
    )
    income = models.DecimalField(
        verbose_name='Прибыль',
        help_text='Сумма прибыли по сделке',
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
    )
    profitability = models.DecimalField(
        verbose_name='Рентабельность',
        help_text='Рентабельность сделки в процентах',
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
    )
    company_id = models.PositiveIntegerField(
        verbose_name='ID компании',
        help_text='ID компании сделки из Битрикс24',
        null=True,
        blank=True,
    )
    company_name = models.CharField(
        verbose_name='Наименование компании',
        help_text='Наименование компании сделки из Битрикс24',
        max_length=1024,
        null=True,
        blank=True,
    )
    manager_id = models.PositiveIntegerField(
        verbose_name='ID менеджера',
        help_text='ID менеджера сделки из Битрикс24',
        null=True,
        blank=True,
    )
    manager_name = models.CharField(
        verbose_name='Менеджер',
        help_text='Имя менеджера сделки из Битрикс24',
        max_length=512,
        null=True,
        blank=True,
    )
    closed = models.BooleanField(
        verbose_name='Сделка закрыта',
        default=False,
    )
    start_date = models.DateField(
        verbose_name='Дата создания сделки',
        help_text='Дата создания сделки в Битрикс24',
        null=True,
        blank=True,
    )
    create_date = models.DateTimeField(
        verbose_name='Дата создания',
        auto_now_add=True,
    )
    update_date = models.DateTimeField(
        verbose_name='Дата изменения',
        auto_now=True,
    )

    class Meta:
        verbose_name = 'Сделка'
        verbose_name_plural = 'Сделки'
        ordering = ['update_date']
        unique_together = ['deal_id', 'portal']

    def __str__(self):
        return 'Затраты #{pk}'.format(pk=self.pk)

expenses/dealcard/forms.py
from django import forms

from .models import Expenses, Cargo, CompaniesExpense, Employee


class ExpensesForm(forms.ModelForm):
    """Форма Затрат для услуги"""

    def __init__(self, *args, **kwargs):
        portal = kwargs.pop('portal')
        deal_id = kwargs.pop('deal_id')
        super(ExpensesForm, self).__init__(*args, **kwargs)
        self.fields['cost_item'].empty_label = None
        self.fields['cargo'] = forms.ModelChoiceField(
            required=False,
            queryset=Cargo.objects.filter(portal=portal, deal_id=deal_id),
            label='Груз'
        )
        self.fields['company'] = forms.ModelChoiceField(
            required=False,
            queryset=CompaniesExpense.objects.filter(portal=portal),
            label='Компания'
        )
        self.fields['employee'] = forms.ModelChoiceField(
            required=False,
            queryset=Employee.objects.filter(portal=portal),
            label='Сотрудник'
        )
        self.fields['expense'].widget.attrs['readonly'] = True

    class Meta:
        model = Expenses
        fields = ('cost_item', 'count', 'price', 'expense', 'cargo', 'company',
                  'employee', 'type_cost', 'document')

expenses/templates/dealcard/add_expense.html
{% extends 'base_deal.html' %}

{% block title %}{% if is_edit %}Изменить затраты{% else %}Добавить затраты к услуге{% endif %}{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">{% if is_edit %}Изменить затраты{% else %}Добавить затраты к услуге{% endif %}</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="
                    {% if is_edit %}
                      {% url 'dealcard:edit_expense' expense_id %}?deal_id={{ deal_id }}&member_id={{ member_id }}
                    {% else %}
                      {% url 'dealcard:add_expense' %}?deal_id={{ deal_id }}&product_id={{ product_id }}&member_id={{ member_id }}
                    {% endif %}">
              {% csrf_token %}
              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {% if field|fieldtype == 'Select' %}
                    {{ field|addclass:'form-select shadow-none' }}
                  {% else %}
                    {{ field|addclass:'form-control shadow-none' }}
                  {% endif %}
                    {% if field.help_text %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button
                        type="submit"
                        class="btn btn-primary shadow-none"
                >
                  {% if is_edit %}Сохранить{% else %}Добавить{% endif %}
                </button>
                <a
                        href="{% url 'dealcard:card' %}?member_id={{ member_id }}&deal_id={{ deal_id }}"
                        class="btn btn-danger shadow-none"
                >
                  Отмена
                </a>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->

{#  <div class="modal fade" id="modal_calc" tabindex="-1">#}
{#    <div class="modal-dialog">#}
{#      <div class="modal-content">#}
{#        <div class="modal-header">#}
{#          <h5 class="modal-title">Расчет суммы</h5>#}
{#          <button type="button" class="btn-close" data-bs-dismiss="modal"></button>#}
{#        </div>#}
{#        <div class="modal-body">#}
{#          <form>#}
{#            <div class="mb-3">#}
{#              <label for="count" class="col-form-label">Количество:</label>#}
{#              <input type="text" class="form-control" id="count" onkeyup="calculate_sum()" value="0">#}
{#            </div>#}
{#            <div class="mb-3">#}
{#              <label for="price" class="col-form-label">Цена:</label>#}
{#              <input type="text" class="form-control" id="price" onkeyup="calculate_sum()" value="0">#}
{#            </div>#}
{#            <div class="mb-3">#}
{#              <label for="sum" class="col-form-label">Сумма:</label>#}
{#              <input type="text" class="form-control" id="sum">#}
{#            </div>#}
{#          </form>#}
{#        </div>#}
{#        <div class="modal-footer">#}
{#          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Закрыть</button>#}
{#          <button type="button" class="btn btn-success" id="btn_save_sum" data-bs-dismiss="modal">Сохранить</button>#}
{#        </div>#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
{% endblock %}
{% block resize %}
  <script>
    {#$("#id_expense").focus(function() {#}
    {#  const modal = new bootstrap.Modal(document.querySelector('#modal_calc'));#}
    {#  modal.show();#}
    {#);#}
    {##}
    {#$("#btn_save_sum").on("click", function () {#}
    {#    document.getElementById("id_expense").value = document.getElementById("sum").value;#}
    {#)#}
    {##}
    let count = document.getElementById('id_count');
    count.addEventListener('keyup', calculate_sum);
    count.addEventListener('change', calculate_sum);
    let price = document.getElementById('id_price');
    price.addEventListener('keyup', calculate_sum);
    price.addEventListener('change', calculate_sum);
    {#let expense = document.getElementById('id_expense');#}
    {#expense.att#}

    function calculate_sum() {
        const count = document.getElementById("id_count");
        const price = document.getElementById("id_price");
        const expense = document.getElementById("id_expense");
        expense.value = (count.value * price.value).toFixed(2);
    }



    $(document).ready(function ()
    {
        $('#id_company').select2({
            theme: "bootstrap-5",
            selectionCssClass: "shadow-none",
        });
        $('#id_cost_item').select2({
            theme: "bootstrap-5",
            selectionCssClass: "shadow-none",
        });
        $('#id_employee').select2({
            theme: "bootstrap-5",
            selectionCssClass: "shadow-none",
        });
        $('#id_cargo').select2({
            theme: "bootstrap-5",
            selectionCssClass: "shadow-none",
        });
        $('#id_type_cost').select2({
            theme: "bootstrap-5",
            selectionCssClass: "shadow-none",
        });
    });
  </script>
  <script type="text/javascript">
    BX24.resizeWindow(1024, 860);
  </script>
{% endblock %}

expenses/templates/dealcard/card.html
{% extends 'base_deal.html' %}

{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div class="container mt-5">
    <div class="row row-cols-2 row-cols-lg-4 row-cards">
      <div class="col">
        <div class="card card-calc text-center">
          <div class="card-header blue">
            <span>Выручка, руб.</span>
          </div>
          <div class="card-body">
            <span>{{ calculations.proceeds }}</span>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card card-calc text-center">
          <div class="card-header blue">
            <span>Затраты, руб.</span>
          </div>
          <div class="card-body">
            <span>{{ calculations.sum_expenses }}</span>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card card-calc text-center">
          <div class="card-header blue">
            <span>Прибыль, руб.</span>
          </div>
          <div class="card-body">
            <span>{{ calculations.income }}</span>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card card-calc text-center">
          <div class="card-header blue">
            <span>Рентабельность, %</span>
          </div>
          <div class="card-body">
            <span>{{ calculations.profitability }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    {% load user_filters %}
    {% for product in bx24_obj.deal_products %}
      <table class="table table-border table-margin-top table-products">
        <thead>
          <tr>
            <th class="col-1" scope="col">#</th>
            <th class="col-3" scope="col">Наименование услуги</th>
            <th class="col-2" scope="col">Цена, руб.</th>
            <th class="col-1" scope="col">Кол-во</th>
            <th class="col-2" scope="col">Сумма без НДС, руб.</th>
            <th class="col-1" scope="col">НДС, %</th>
            <th class="col-2" scope="col">Сумма с НДС, руб.</th>
          </tr>
        </thead>
        <tbody>
          <tr class="tr-green">
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ product.PRODUCT_NAME }}</td>
            <td>{{ product.PRICE_EXCLUSIVE|floatformat:2 }}</td>
            <td>{{ product.QUANTITY }}</td>
            <td>{% multiply product.PRICE_EXCLUSIVE product.QUANTITY %}</td>
            <td>{{ product.TAX_RATE }}</td>
            <td>{% multiply product.PRICE product.QUANTITY %}</td>
          </tr>
        </tbody>
      </table>
      <div class="card card-expenses">
        <div class="card-header">
          Затраты
        </div>
        <div class="card-body">
          <table class="table table-border table-striped">
            <thead>
              <tr>
                <th scope="col" width="30%">Статья затрат</th>
                <th scope="col" width="10%">Сумма, руб.</th>
                <th scope="col" width="10%">Груз</th>
                <th scope="col" width="10%">Компания</th>
                <th scope="col" width="10%">Сотрудник</th>
                <th scope="col" width="10%">Вид оплаты</th>
                <th scope="col" width="10%">Документ</th>
                <th scope="col" width="10%">Действия</th>
              </tr>
            </thead>
            <tbody>
              {% load user_filters %}
              {% for expense in expenses %}
                {% if expense.product_id == product.ID|to_int %}
                  <tr>
                    <td>{{ expense.cost_item }}</td>
                    <td>{{ expense.expense}}</td>
                    <td>{{ expense.cargo|emptyvalue }}</td>
                    <td>{{ expense.company|emptyvalue }}</td>
                    <td>{{ expense.employee|emptyvalue }}</td>
                    <td>{{ expense.type_cost|emptyvalue }}</td>
                    <td>{{ expense.document|emptyvalue }}</td>
                    <td>
                      <a
                              href="{% url 'dealcard:edit_expense' expense.pk %}?deal_id={{ deal_id }}&member_id={{ portal.member_id }}"
                              class="btn btn-primary shadow-none btn-small"
                              title="Изменить"
                      >
                        🗘
                      </a>
                      <a
                              href="{% url 'dealcard:add_expense' %}?deal_id={{ deal_id }}&product_id={{ product.ID }}&member_id={{ portal.member_id }}&expense={{ expense.pk }}"
                              class="btn btn-info shadow-none btn-small"
                              title="Копировать"
                      >
                        📑
                      </a>
                      <a
                              href="{% url 'dealcard:delete_expense' expense.pk %}?deal_id={{ deal_id }}&member_id={{ portal.member_id }}"
                              class="btn btn-danger shadow-none btn-small"
                              title="Удалить"
                      >
                        ✖
                      </a>
                    </td>
                  </tr>
                {% endif %}
              {% endfor %}
            </tbody>
          </table>
        </div>

        <div class="card-footer">
          <a
                  href="{% url 'dealcard:add_expense' %}?deal_id={{ deal_id }}&product_id={{ product.ID }}&member_id={{ portal.member_id }}"
                  class="btn btn-primary shadow-none"
          >
            Добавить затраты к услуге
          </a>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

expenses/templates/dealcard/no_products.html
{% extends 'base_deal.html' %}

{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div class="container mt-5">
    <div class="alert alert-warning" role="alert">
      В данной сделке отсутствуют товары. Внесение затрат невозможно.<br>
      1. Перейдите на вкладку "Товары" и добавьте позиции.<br>
      2. Обновите страницу в браузере.
    </div>
  </div>
{% endblock %}