expenses/expenses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainpage.urls', namespace='mainpage')),
    path('card/', include('dealcard.urls', namespace='dealcard')),
    path('admin/', admin.site.urls),
    path('reports/', include('reports.urls', namespace='reports')),
]

expenses/mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.index, name='index'),
    path('install/', views.install, name='install'),
]

expenses/reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'

urlpatterns = [
    path('finance/', views.report_finance, name='report_finance'),
    path('buh/', views.report_buh, name='report_buh')
]

expenses/reports/forms.py
from django import forms

from dealcard.models import CompaniesExpense


class ReportFinanceForm(forms.Form):
    """Форма параметров отчета финансиста"""

    DEAL_TYPE_CHOICES = [
        ('close', 'Закрытые'),
        ('open', 'Открытые'),
        ('all', 'Все'),
    ]

    deal_type = forms.ChoiceField(
        label='Тип сделок',
        choices=DEAL_TYPE_CHOICES,
    )

    start_date = forms.DateField(
        label='Начальная дата',
        widget=forms.widgets.DateInput(attrs={
            'type': 'date',
            'class': 'form-control datepicker-input',
        })
    )

    end_date = forms.DateField(
        label='Конечная дата',
        widget=forms.widgets.DateInput(attrs={
            'type': 'date',
            'class': 'form-control datepicker-input',
        })
    )


class ReportBuhForm(forms.Form):
    """Форма параметров отчета бухгалтера"""

    NO_COMPANY_VISIBLE_CHOICES = [
        ('y', 'Показывать'),
        ('n', 'Не показывать'),
    ]

    start_date = forms.DateField(
        label='Начальная дата',
        widget=forms.widgets.DateInput(attrs={
            'type': 'date',
            'class': 'form-control datepicker-input',
        }),
        required=False,
    )

    end_date = forms.DateField(
        label='Конечная дата',
        widget=forms.widgets.DateInput(attrs={
            'type': 'date',
            'class': 'form-control datepicker-input',
        }),
        required=False,
    )

    no_company_visible = forms.ChoiceField(
        label='Показывать без поставщика',
        choices=NO_COMPANY_VISIBLE_CHOICES,
    )

    company = forms.ModelChoiceField(
        label='Поставщик',
        queryset=CompaniesExpense.objects.all(),
        required=False,
    )

    document = forms.CharField(
        label='Документ',
        required=False,
    )

    sum = forms.DecimalField(
        label='Сумма',
        required=False,
    )

expenses/reports/views.py
import decimal
from django.shortcuts import render
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.csrf import csrf_exempt
from django.utils.dateparse import parse_date

from .forms import ReportFinanceForm, ReportBuhForm
from dealcard.models import Expenses, CompaniesExpense, Deal
from mainpage.models import Portals


@xframe_options_exempt
@csrf_exempt
def report_finance(request):
    template: str = 'reports/report_finance.html'

    member_id: str = request.GET.get('member_id')
    portal: Portals = Portals.objects.get(member_id=member_id)

    form: ReportFinanceForm = ReportFinanceForm(request.POST or None)
    context = {
        'form': form,
        'member_id': member_id,
    }
    if not form.is_valid():
        return render(request, template, context)
    deal_type = request.POST.get('deal_type')
    start_date = request.POST.get('start_date')
    end_date = request.POST.get('end_date')
    deals_for_reports: list[dict[str, any]] = list(dict())
    deals = Deal.objects.filter(portal=portal)
    if deals.count() != 0:
        for deal in deals:
            if deal_type == 'close' and not deal.closed:
                continue
            elif deal_type == 'open' and deal.closed:
                continue
            if not (parse_date(start_date) <= deal.start_date <= parse_date(end_date)):
                continue

            deals_for_reports.append(
                {
                    'deal_id': deal.deal_id,
                    'manager': deal.manager_name,
                    'opportunity': deal.proceeds,
                    'sum_expenses': deal.sum_expenses,
                    'profitability': deal.profitability,
                    'income': deal.income,
                    'portal_name': portal.name,
                    'company': deal.company_name,
                    'company_id': deal.company_id,
                }
            )
        context['deals_for_reports'] = deals_for_reports
    return render(request, template, context)


@xframe_options_exempt
@csrf_exempt
def report_buh(request):
    template: str = 'reports/report_buh.html'

    member_id: str = request.GET.get('member_id')
    portal: Portals = Portals.objects.get(member_id=member_id)

    form: ReportBuhForm = ReportBuhForm(request.POST or None)
    context = {
        'form': form,
        'member_id': member_id,
    }
    if not form.is_valid():
        return render(request, template, context)

    expenses_for_reports: list[dict[str, any]] = list(dict())
    total_sum = decimal.Decimal(0.00)
    expenses_deals = (Expenses.objects
                      .select_related('company')
                      .filter(portal=portal)
                      )
    for expense in expenses_deals:
        if request.POST.get('company'):
            company_pk = int(request.POST.get('company'))
            company = CompaniesExpense.objects.get(pk=company_pk)
            if not expense.company:
                continue
            elif company.pk != expense.company.pk:
                continue
        if request.POST.get('start_date') and request.POST.get('end_date'):
            start_date = request.POST.get('start_date')
            end_date = request.POST.get('end_date')
            if not (parse_date(start_date) <= expense.create_date.date()
                    <= parse_date(end_date)):
                continue
        elif request.POST.get('start_date'):
            start_date = request.POST.get('start_date')
            if parse_date(start_date) > expense.create_date.date():
                continue
        elif request.POST.get('end_date'):
            end_date = request.POST.get('end_date')
            if parse_date(end_date) < expense.create_date.date():
                continue
        if request.POST.get('sum'):
            sum_expense = decimal.Decimal(request.POST.get('sum'))
            if sum_expense != expense.expense:
                continue
        if request.POST.get('no_company_visible') == 'n' and not expense.company:
            continue
        if request.POST.get('document'):
            document = request.POST.get('document')
            if not expense.document:
                continue
            elif not document.lower() in expense.document.lower():
                continue
        expenses_for_reports.append(
            {
                'date': expense.create_date,
                'company': expense.company,
                'company_id': expense.company,
                'deal_id': expense.deal_id,
                'sum_expense': expense.expense,
                'document': expense.document,
                'portal_name': portal.name,
            }
        )
        total_sum += expense.expense
    context['expenses_for_reports'] = expenses_for_reports
    context['total_sum'] = total_sum
    return render(request, template, context)

expenses/templates/reports/report_buh.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div class="container mt-3 filter-menu">
    <div class="card card-calc">
      <div class="card-header blue">
        Действия
      </div>
      <div class="card-body">
        {% load user_filters %}
        <form method="post" action="{% url 'reports:report_buh' %}?member_id={{ member_id }}">
          {% csrf_token %}
          <div class="row row-cols-3 mb-2">
            {% for field in form %}
              <div class="form-group col">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                {% if field|fieldtype == 'Select' %}
                  {{ field|addclass:'form-select shadow-none mb-3' }}
                {% else %}
                  {{ field|addclass:'form-control shadow-none mb-3' }}
                {% endif %}
                  {% if field.help_text %}
                    <small
                       id="{{ field.id_for_label }}-help"
                       class="form-text text-muted"
                    >
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
              </div>
            {% endfor %}
          </div>
          <div class="row row-cols-auto justify-content-end">
            <div class="col">
              <button
                      type="submit"
                      class="btn btn-primary shadow-none"
              >Применить</button>
            </div>
          </div>
        </form>
      </div>
      <div class="card-footer justify-content-end">
        <div class="row row-cols-auto justify-content-end">
          <div class="col">
            <button class="btn btn-success shadow-none" onclick="tableToExcel('report-buh')">Выгрузить в Excel</button>
          </div>
          <div class="col">
            <a
                    href="{% url 'mainpage:index' %}?member_id={{ member_id }}"
                    class="btn btn-danger shadow-none"
            >На главную</a>
          </div>
        </div>
      </div>
    </div>
  <script>
</script>


  </div>
  <div class="container report-area">
    <table class="table table-border table-striped table-reports" id="report-buh">
      <thead>
        <tr>
          <th>Дата</th>
          <th>Поставщик</th>
          <th>Сделка</th>
          <th>Документ</th>
          <th>Сумма, руб.</th>
        </tr>
      </thead>
      <tbody>
          {% for expense in expenses_for_reports %}
            <tr>
              <td>{{ expense.date|date:"d.m.Y" }}</td>
              {% if expense.company %}
                <td><a href="https://{{ expense.portal_name }}/crm/company/details/{{ expense.company_id.id_b24 }}/" target="_blank">{{ expense.company }}</a></td>
              {% else %}
                <td>---</td>
              {% endif %}
              <td><a href="https://{{ expense.portal_name }}/crm/deal/details/{{ expense.deal_id }}/" target="_blank">Сделка №{{ expense.deal_id }}</a></td>
              {% if expense.document %}
                <td>{{ expense.document }}</td>
              {% else %}
                <td>---</td>
              {% endif %}
              <td>{{ expense.sum_expense }}</td>
            </tr>
          {% endfor %}
      </tbody>
      <tfoot>
        <tr>
          <th colspan="5" style="text-align: right">Итого: {{ total_sum }} руб.</th>
        </tr>
      </tfoot>
    </table>

  </div>
{% endblock %}
{% block scripts %}
  <script>
    $(document).ready(function() {
      $("#report-buh").DataTable({
        searching: false,
        paging: false,
        info: false,
        autoWidth: false,
        language: {
          zeroRecords: 'Записи не найдены',
          emptyTable: 'Записи не найдены',
        },
        columnDefs: [
          { className: 'col-2', targets: [0, 2, 4] },
          { className: 'col-3', targets: [1, 3] },
        ]
      });
    });
  </script>
  <script>
    $(document).ready(function() {
      $('#import-excel').attr('disabled', false);
      var excel_data = $('#report-buh').html();
      $('#xls_data').val(excel_data);
    });
  </script>
  <script>
    var tableToExcel = (function() {
      var uri = 'data:application/vnd.ms-excel;base64,',
      template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>',
      base64 = function(s) {return window.btoa(unescape(encodeURIComponent(s)))},
      format = function(s, c) {
          return s.replace(/{(\w+)}/g, function (m, p) {
              return c[p];
          })
      },
      downloadURI = function(uri, name) {
        var link = document.createElement("a");
        link.download = name;
        link.href = uri;
        link.click();
      }
      return function(table, name) {
        if (!table.nodeType) table = document.getElementById(table)
        var ctx = {
          worksheet: name || 'Worksheet',
          table: table.innerHTML
        }
        var resuri = uri + base64(format(template, ctx))
        downloadURI(resuri, 'ReportBuh.xls');
      }
    })();
  </script>
  <script>
    $(document).ready(function ()
    {
        $('#id_company').select2({
            theme: "bootstrap-5",
            selectionCssClass: "shadow-none",
        });
    });
  </script>
{% endblock %}

expenses/templates/reports/report_finance.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div class="container mt-3 filter-menu">
    <div class="card card-calc">
      <div class="card-header blue">
        Действия
      </div>
      <div class="card-body">
        {% load user_filters %}
        <form method="post" action="{% url 'reports:report_finance' %}?member_id={{ member_id }}">
          {% csrf_token %}
          <div class="row row-cols-3 mb-2">
            {% for field in form %}
              <div class="form-group col">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                {% if field|fieldtype == 'Select' %}
                  {{ field|addclass:'form-select shadow-none' }}
                {% else %}
                  {{ field|addclass:'form-control shadow-none' }}
                {% endif %}
                  {% if field.help_text %}
                    <small
                       id="{{ field.id_for_label }}-help"
                       class="form-text text-muted"
                    >
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
              </div>
            {% endfor %}
          </div>
          <div class="row row-cols-auto justify-content-end">
            <div class="col">
              <button
                      type="submit"
                      class="btn btn-primary shadow-none"
              >Применить</button>
            </div>
          </div>
        </form>
      </div>
      <div class="card-footer justify-content-end">
        <div class="row row-cols-auto justify-content-end">
          <div class="col">
            <button class="btn btn-success shadow-none" onclick="tableToExcel('report-finance')">Выгрузить в Excel</button>
          </div>
          <div class="col">
            <a
                    href="{% url 'mainpage:index' %}?member_id={{ member_id }}"
                    class="btn btn-danger shadow-none"
            >На главную</a>
          </div>
        </div>
      </div>
    </div>
  <script>
</script>


  </div>
  <div class="container report-area">
    <table class="table table-border table-striped table-reports" id="report-finance">
      <thead>
        <tr>
          <th>Сделка</th>
          <th>Менеджер</th>
          <th>Контрагент</th>
          <th>Сумма сделки, руб.</th>
          <th>Сумма расходов, руб.</th>
          <th>Рентаб-сть, %</th>
          <th>Прибыль, руб.</th>
        </tr>
      </thead>
      <tbody>
          {% for deal in deals_for_reports %}
            <tr>
              <td><a href="https://{{ deal.portal_name }}/crm/deal/details/{{ deal.deal_id }}/" target="_blank">Сделка №{{ deal.deal_id }}</a></td>
              <td>{{ deal.manager }}</td>
              {% if deal.company_id == 'error' %}
                <td class="table-danger">{{ deal.company }}</td>
              {% else %}
                <td><a href="https://{{ deal.portal_name }}/crm/company/details/{{ deal.company_id }}/" target="_blank">{{ deal.company }}</a></td>
              {% endif %}
              <td>{{ deal.opportunity }}</td>
              <td>{{ deal.sum_expenses }}</td>
              <td>{{ deal.profitability }}</td>
              <td>{{ deal.income }}</td>
            </tr>
          {% endfor %}
      </tbody>
    </table>

  </div>
{% endblock %}
{% block scripts %}
  <script>
    $(document).ready(function() {
      $("#report-finance").DataTable({
        searching: false,
        paging: false,
        info: false,
        autoWidth: false,
        language: {
          zeroRecords: 'Записи не найдены',
          emptyTable: 'Записи не найдены',
        },
        columnDefs: [
          { className: 'col-2', targets: 0 },
          { className: 'col-3', targets: [1, 2] },
          { className: 'col-1', targets: "_all" },
        ]
      });
    });
  </script>
  <script>
    $(document).ready(function() {
      $('#import-excel').attr('disabled', false);
      var excel_data = $('#report-finance').html();
      $('#xls_data').val(excel_data);
    });
  </script>
  <script>
    var tableToExcel = (function() {
      var uri = 'data:application/vnd.ms-excel;base64,',
      template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>',
      base64 = function(s) {return window.btoa(unescape(encodeURIComponent(s)))},
      format = function(s, c) {
          return s.replace(/{(\w+)}/g, function (m, p) {
              return c[p];
          })
      },
      downloadURI = function(uri, name) {
        var link = document.createElement("a");
        link.download = name;
        link.href = uri;
        link.click();
      }
      return function(table, name) {
        if (!table.nodeType) table = document.getElementById(table)
        var ctx = {
          worksheet: name || 'Worksheet',
          table: table.innerHTML
        }
        var resuri = uri + base64(format(template, ctx))
        downloadURI(resuri, 'ReportFinance.xls');
      }
    })();
  </script>
{% endblock %}